# Generated by Django 4.2 on 2023-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='weight_after',
        ),
        migrations.RemoveField(
            model_name='race',
            name='weight_before',
        ),
        migrations.AddField(
            model_name='driver',
            name='weight_after',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='weight_before',
            field=models.FloatField(default=0),
        ),
    ]
