# Generated by Django 4.2 on 2023-06-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_race_weight_after_remove_race_weight_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
